In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [7]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [9]:
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...      False        False       False   
1    137.528754  4.627244  10.700000  ...       True        False       False   
2    138.000000  4.400000  12.000000  ...       True        False       False   
3    138.000000  3.200000   8.100000  ...       True        False       False   
4    137.528754  4.627244  11.800000  ...       True        False       False   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...       True        False       False   
395  137.528754  4.627244   8.700000  ...       True        False       False   
396  134.000000  2.700000   9.100000  ...       True        False       False   
397  142.000000  5.500000   8.500000  ...       True        False       False   
398  140.000000  5.000000  16.300000  ...       True        False       False   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0      False   False    False       True    True    False                True  
1      False   False    False       True   False    False                True  
2      False   False    False       True   False    False                True  
3      False   False    False       True   False     True                True  
4      False   False    False       True   False    False                True  
..       ...     ...      ...        ...     ...      ...                 ...  
394    False   False    False       True   False    False                True  
395     True    True    False       True   False     True                True  
396     True    True    False      False   False    False                True  
397     True    True    False       True   False     True                True  
398    False   False    False       True   False    False               False  

[399 rows x 28 columns]

In [11]:
dataset=dataset.astype(int)

In [13]:
dataset

age  bp  al  su  bgr   bu  sc  sod  pot  hrmo  ...  pc_normal  \
0      2  76   3   0  148   57   3  137    4    12  ...          0   
1      3  76   2   0  148   22   0  137    4    10  ...          1   
2      4  76   1   0   99   23   0  138    4    12  ...          1   
3      5  76   1   0  148   16   0  138    3     8  ...          1   
4      5  50   0   0  148   25   0  137    4    11  ...          1   
..   ...  ..  ..  ..  ...  ...  ..  ...  ...   ...  ...        ...   
394   51  70   0   0  219   36   1  139    3    12  ...          1   
395   51  70   0   2  220   68   2  137    4     8  ...          1   
396   51  70   3   0  110  115   6  134    2     9  ...          1   
397   51  90   0   0  207   80   6  142    5     8  ...          1   
398   51  80   0   0  100   49   1  140    5    16  ...          1   

     pcc_present  ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  \
0              0           0        0       0        0          1       1   
1              0           0        0       0        0          1       0   
2              0           0        0       0        0          1       0   
3              0           0        0       0        0          1       0   
4              0           0        0       0        0          1       0   
..           ...         ...      ...     ...      ...        ...     ...   
394            0           0        0       0        0          1       0   
395            0           0        1       1        0          1       0   
396            0           0        1       1        0          0       0   
397            0           0        1       1        0          1       0   
398            0           0        0       0        0          1       0   

     ane_yes  classification_yes  
0          0                   1  
1          0                   1  
2          0                   1  
3          1                   1  
4          0                   1  
..       ...                 ...  
394        0                   1  
395        1                   1  
396        0                   1  
397        1                   1  
398        0                   0  

[399 rows x 28 columns]

In [15]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [17]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [19]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset["classification_yes"]

In [21]:
indep.shape

(399, 27)

In [23]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int64

In [25]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [26]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.69      0.98      0.81        51
           1       0.98      0.73      0.84        82

    accuracy                           0.83       133
   macro avg       0.84      0.86      0.83       133
weighted avg       0.87      0.83      0.83       133

[[50  1]
 [22 60]]


In [43]:
classifier.predict([[20,60,0,0,148,57,3,137,4.7,14,41,4500,5.5,1,0,0,0,1,1,0,0,0,0,0,1,0,0]])

/Users/sutharsanurudrasingam/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but ComplementNB was fitted with feature names
  warnings.warn(


array([1])

In [29]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.85      1.00      0.92        51
           1       1.00      0.89      0.94        82

    accuracy                           0.93       133
   macro avg       0.93      0.95      0.93       133
weighted avg       0.94      0.93      0.93       133

[[51  0]
 [ 9 73]]


In [41]:
classifier.predict([[20,60,0,0,148,57,3,137,4.7,14,41,4500,5.5,1,0,0,0,1,1,0,0,0,0,0,1,0,0]])

/Users/sutharsanurudrasingam/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but ComplementNB was fitted with feature names
  warnings.warn(


array([1])

In [33]:
from sklearn.naive_bayes import CategoricalNB
classifier =CategoricalNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

IndexError: index 90 is out of bounds for axis 1 with size 84

In [45]:
classifier.predict([[20,60,0,0,148,57,3,137,4.7,14,41,4500,5.5,1,0,0,0,1,1,0,0,0,0,0,1,0,0]])

/Users/sutharsanurudrasingam/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but ComplementNB was fitted with feature names
  warnings.warn(


array([1])

In [37]:
from sklearn.naive_bayes import ComplementNB
classifier =ComplementNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.69      0.98      0.81        51
           1       0.98      0.73      0.84        82

    accuracy                           0.83       133
   macro avg       0.84      0.86      0.83       133
weighted avg       0.87      0.83      0.83       133

[[50  1]
 [22 60]]


In [39]:
classifier.predict([[20,60,0,0,148,57,3,137,4.7,14,41,4500,5.5,1,0,0,0,1,1,0,0,0,0,0,1,0,0]])

/Users/sutharsanurudrasingam/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but ComplementNB was fitted with feature names
  warnings.warn(


array([1])